### ISSUE TITLE
Error while parsing Dockerfile 

### ISSUE THREAD

**Issue by HRouhani** [mondoohq/cnquery#4269] opened 2024-06-19 14:22 UTC
**Description:**
I am encountering errors while using cnquery to parse a Dockerfile. The errors indicate that certain primitives cannot be converted due to missing type information.

Dockerfile Content example:

```
# Use an official Python runtime as a parent image for the builder stage
FROM python:3.9-slim AS builder

# Set the working directory in the builder stage
WORKDIR /app

# Copy the requirements file into the builder stage
COPY requirements.txt ./

# Install the dependencies in the builder stage
RUN pip install --no-cache-dir -r requirements.txt

# Use an official Python runtime as a parent image for the final stage
FROM python:3.9-slim

# Set environment variables
ENV FLASK_APP=app/__init__.py
ENV FLASK_ENV=production
ENV PORT=5000

# Set the working directory in the final stage
WORKDIR /app

# Copy the dependencies from the builder stage
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy the application code into the final stage
COPY app ./app

# Ensure gunicorn is installed
RUN pip install gunicorn

# Expose the port the app runs on
EXPOSE 5000

# Health check to ensure the application is running
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:5000/health || exit 1

# Command to run the application
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
```

**Error Message:**
![image](https://github.com/mondoohq/cnquery/assets/56231339/91566e44-0fd7-4d55-b081-6d597d6bad4b)

**Steps to Reproduce:**

1.     Use cnquery to parse the Dockerfile.
2.     Observe the errors related to missing type information for various Dockerfile commands.

**Expected Behavior:**
The Dockerfile should be parsed without errors, and all commands should be correctly interpreted with appropriate type information.

**Comment by slntopp** [comment] 2024-07-08 18:58
This appears to be intended behaviour, resources such as 
- `docker.file.expose`
- `docker.file.run`
- `docker.file.cmd`
- `docker.file.entrypoint`
- `docker.file.from`
- `docker.file.user`
- `docker.file.add`
- `docker.file.copy`

should be retrieved via `docker.file.stages[x].<resource>`

and resource `docker.file.stage` should be retrieved via `docker.file.stages[x]`

Confusion should be resolved with:
#4319 
#4321

**Closed** 2024-07-08 21:04 UTC
