### ISSUE TITLE
scan running container panics in azure discovery

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#1950] opened 2023-09-27 10:10 UTC
**Describe the bug**
```
cnspec-v9 scan container bc7fbc466c7c --config ~/workspace/mondoo/sa-prod-us-default.json                                                             
! CLI pre-processing encountered an issue error="unknown flag: --config"
→ loaded configuration from /home/christian/workspace/mondoo/sa-prod-us-default.json using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
→ synchronize assets

 musing_hermann ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   0%


panic: assignment to entry in nil map

goroutine 16 [running]:
go.mondoo.com/cnquery/providers/azure/resources.getSubConfig(0x0?, {0xc0005841e0, {0x184e700, 0x0, 0x0}, 0xc000012600, 0xc00058a180, 0xc0005841d0, 0xc000584160, 0xc0005840f0, ...})
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/resources/discovery.go:643 +0x85
go.mondoo.com/cnquery/providers/azure/resources.Discover(0xc00043ed80, 0xc0001de780)
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/resources/discovery.go:87 +0x2f8
go.mondoo.com/cnquery/providers/azure/provider.(*Service).discover(0xc0001f1870?, 0xc000257bc0, 0x1137b98?)
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/provider/provider.go:281 +0xe5
go.mondoo.com/cnquery/providers/azure/provider.(*Service).Connect(0xc0002ee100?, 0xc0000996e0, {0x1137b98?, 0xc000433310?})
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/provider/provider.go:132 +0x6f
go.mondoo.com/cnquery/providers-sdk/v1/plugin.(*GRPCServer).Connect(0xc000037cc0, {0xc0000996e0?, 0x4cc226?}, 0xc0000996e0)
	/home/christian/workspace/mondoo/github.com/cnquery/providers-sdk/v1/plugin/grpc.go:92 +0xd5
go.mondoo.com/cnquery/providers-sdk/v1/plugin._ProviderPlugin_Connect_Handler({0xf251c0?, 0xc000037cc0}, {0x113a3c0, 0xc00041c000}, 0xc0002d6bd0, 0x0)
	/home/christian/workspace/mondoo/github.com/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:179 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002401e0, {0x113f178, 0xc00024d6c0}, 0xc000249c20, 0xc000287710, 0x180e678, 0x0)
	/home/christian/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:1376 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002401e0, {0x113f178, 0xc00024d6c0}, 0xc000249c20, 0x0)
	/home/christian/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:1753 +0x9e7

 musing_hermann ━━───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   1%
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 12
	/home/christian/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:996 +0x165
```

The image for this container is a alpine based nginx. This shouldn't trigger azure discovery at all.

**To Reproduce**

1. Run container with image `nginx:alpine`
2. Run above command against the container
3. Note the error

**Expected behavior**
No azure discovery, no panic.

**Desktop (please complete the following information):**

- cnspec beta4

**Comment by czunker** [comment] 2023-09-27 12:26
Platform IDs are wrong.

v9
```
./cnquery run container bc7fbc466c7c -c "asset{ platform ids name title }" --config ~/workspace/mondoo/sa-prod-us-default.json                                                                                                               
! CLI pre-processing encountered an issue error="unknown flag: --config"
→ loaded configuration from /home/christian/workspace/mondoo/sa-prod-us-default.json using source --config
asset: {
  title: "Alpine Linux v3.16, Docker Container"
  platform: "alpine"
  ids: [
    0: "bc7fbc466c7c"
  ]
  name: "musing_hermann"
}
```
v8:
```
 ~/Downloads  cnquery run container bc7fbc466c7c -c "asset{ platform ids name title }" --config ~/workspace/mondoo/sa-prod-us-default.json 
→ loaded configuration from /home/christian/workspace/mondoo/sa-prod-us-default.json using source --config
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
asset: {
  title: "Alpine Linux v3.16, Docker Container"
  platform: "alpine"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/docker/containers/bc7fbc466c7c9682217d950d935aead1f415d1b69b6e87c0b0ac801eb513feff"
  ]
  name: "musing_hermann"
}
```

**Comment by czunker** [comment] 2023-09-27 13:14
When I use the query pack locally, I do not see this problem:
```
cnquery scan container bc7fbc466c7c -f ../server/policy/bundles-internal/asset-overview.mql.yaml                                                                       
! using builtin provider for os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ using service account credentials
! Scanning with local bundles will switch into --incognito mode by default. Your results will not be sent upstream.
→ discover related assets for 1 asset(s)
! using builtin provider for os
! using builtin provider for os

 musing_hermann ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────    X


Summary (1 assets)
==================

Target:     musing_hermann
error: bundle doesn't contain any query packs
```

**Comment by vjeffrey** [comment] 2023-09-29 15:34
i think this might be fixed now, ill retest

**Comment by vjeffrey** [comment] 2023-10-02 06:28
i can't reproduce this

**Closed by vjeffrey** 2023-10-02 06:28 UTC
Labels: bug, v9
